# Generated by Django 3.2 on 2026-03-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_specialization', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='da_console.category')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('biography_about_doctor', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('qualifications', models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('MS', 'MS'), ('DM', 'DM')], max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('medical_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_council_name', models.CharField(blank=True, max_length=150, null=True)),
                ('official_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('consultation_languages', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Visiting', 'Visiting'), ('Consultant', 'Consultant')], max_length=30, null=True)),
                ('hospital_clinic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_location', models.CharField(blank=True, max_length=255, null=True)),
                ('room_cabin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('shift_timings', models.CharField(blank=True, max_length=100, null=True)),
                ('on_call_availability', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='da_console.category')),
                ('sub_category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='da_console.sub_category')),
            ],
        ),
    ]
